

Survey
    .StylesManager
    .applyTheme("defaultV2");

var json = localStorage.getItem("jsonText"); 
var from = localStorage.getItem("fromText"); 

// function sendSurveyToStudent(){
//     const surveyRef = ref(database, 'resultHolder/' + from + "-result");
//     // Get the unique ID generated by push() by accessing its key
//     const newPostKey = push(surveyRef).key;
//     const updates = {};
//     updates['resultHolder/' + from + "-result" + newPostKey] = json;
//     // Get the unique ID generated by push() by accessing its key
//     alert("Results are saved!")
//     return update(ref(database), updates);
// }

window.survey = new Survey.Model(json);
survey
    .onComplete
    .add(function (sender) {
        document
            .querySelector('#surveyResult')
            .textContent = JSON.stringify(sender.data, null, 3);
            // sendSurveyToStudent();
    });

ReactDOM.render(<SurveyReact.Survey model={survey}/>, document.getElementById("surveyElement"));